runtime: python312

env_variables:
  SECRET_KEY: "39048u2joirq@@$i0910"
  DATABASE_URL: "sqlite:///../instance/timesheets.db"

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
