name: Deploy to GCP

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > $HOME/gcloud.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json

    - name: Configure Google Cloud CLI
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/zone us-central1-a  # or your desired zone

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet
