name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          version: ${{ github.sha }}
          promote: true

      - name: Set environment variables and deploy
        run: |
          gcloud app deploy app.yaml --project=project023gmail \
            --version=your_version \
            --quiet \
            --env-vars=SECRET_KEY="your_secret_key",DATABASE_URL="sqlite:///../instance/timesheets.db"
