name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v0.4.0
      with:
        deliverables: 'app.yaml'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud config set account dev01-510@***.iam.gserviceaccount.com
